### ISSUE TITLE
Where to download that last released version?

### ISSUE THREAD

**Issue by Accuraty** [xoofx/PHPManager#1]
Though I was able to figure this out, it was not easy. Somewhere in the Download Archive file from the Codeplex Archive there was a file named with a GUID and no extension. Did a little guessing and renamed it to a Zip and it worked. However, that is a little too bizarre for most people (IMHO). 
 
So... is there a more normal way to find and download the last installable release for PHP Manager 1.2 for IIS?

**Comment by xoofx** [comment]
No, just compile it and install it on your own. I used it several years ago, don't use it anymore.

**Comment by Accuraty** [comment]
Unfortunately, I am not a developer. So that is not an option.

**Comment by lextm** [comment]
@Accuraty You can now download from http://www.phpmanager.xyz .

**Comment by Accuraty** [comment]
I went through every page, but must have missed it. Where is the download? Would it not make sense to also include it here as a Release?
